// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoSecureInfo {
    #[prost(bytes="bytes", optional, tag="1")]
    pub sec_sign: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub sec_token: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub sec_extra: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoReserveFields {
    #[prost(bytes="bytes", optional, tag="8")]
    pub client_ip_cookie: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="9")]
    pub flag: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="10")]
    pub env_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="11")]
    pub locale_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag="12")]
    pub qimei: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="13")]
    pub env: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="14")]
    pub new_conn_flag: ::core::option::Option<u32>,
    #[prost(string, optional, tag="15")]
    pub trace_parent: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="16")]
    pub uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="18")]
    pub imsi: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="19")]
    pub network_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="20")]
    pub ip_stack_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="21")]
    pub msg_type: ::core::option::Option<u32>,
    #[prost(string, optional, tag="22")]
    pub trpc_rsp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map="string, string", tag="23")]
    pub trans_info: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag="24")]
    pub sec_info: ::core::option::Option<SsoSecureInfo>,
    #[prost(uint32, optional, tag="25")]
    pub sec_sig_flag: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="26")]
    pub nt_core_version: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="27")]
    pub sso_route_cost: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="28")]
    pub sso_ip_origin: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="30")]
    pub presure_token: ::core::option::Option<::prost::bytes::Bytes>,
}
// @@protoc_insertion_point(module)
