// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchangeRequest {
    #[prost(bytes="bytes", tag="1")]
    pub public_key: ::prost::bytes::Bytes,
    #[prost(uint32, tag="2")]
    pub r#type: u32,
    #[prost(bytes="bytes", tag="3")]
    pub secret: ::prost::bytes::Bytes,
    #[prost(int64, tag="4")]
    pub timestamp: i64,
    #[prost(bytes="bytes", tag="5")]
    pub verify_hash: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchangeResponse {
    #[prost(bytes="bytes", tag="1")]
    pub secret: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub field2: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="3")]
    pub public_key: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchangeRequestBuf {
    #[prost(string, tag="1")]
    pub uin: ::prost::alloc::string::String,
    #[prost(bytes="bytes", tag="2")]
    pub guid: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyExchangeResponseSecret {
    #[prost(bytes="bytes", tag="1")]
    pub session_key: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub session_ticket: ::prost::bytes::Bytes,
    #[prost(uint32, tag="3")]
    pub expiration: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginForwardRequest {
    #[prost(bytes="bytes", tag="1")]
    pub session_ticket: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="3")]
    pub buffer: ::prost::bytes::Bytes,
    #[prost(uint32, tag="4")]
    pub r#type: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginHead {
    #[prost(message, optional, tag="1")]
    pub user_info: ::core::option::Option<NtLoginUserInfo>,
    #[prost(message, optional, tag="2")]
    pub client_info: ::core::option::Option<NtLoginClientInfo>,
    #[prost(message, optional, tag="3")]
    pub app_info: ::core::option::Option<NtLoginAppInfo>,
    #[prost(message, optional, tag="4")]
    pub error_info: ::core::option::Option<NtLoginErrorInfo>,
    #[prost(message, optional, tag="5")]
    pub cookie: ::core::option::Option<NtLoginCookie>,
    #[prost(message, optional, tag="6")]
    pub security_info: ::core::option::Option<NtLoginSecurityInfo>,
    #[prost(message, optional, tag="7")]
    pub sdk_info: ::core::option::Option<NtLoginSdkInfo>,
    #[prost(message, optional, tag="8")]
    pub long_cookie: ::core::option::Option<NtLoginLongCookie>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginUserInfo {
    #[prost(string, tag="1")]
    pub account: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub country_code: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginClientInfo {
    #[prost(string, tag="1")]
    pub device_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(enumeration="NtLoginPlatform", tag="3")]
    pub platform: i32,
    #[prost(bytes="bytes", tag="4")]
    pub guid: ::prost::bytes::Bytes,
    #[prost(uint32, tag="5")]
    pub pubno: u32,
    #[prost(uint32, tag="6")]
    pub client_ver: u32,
    #[prost(uint32, tag="7")]
    pub client_type: u32,
    #[prost(uint32, tag="8")]
    pub sso_ver: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginAppInfo {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub app_id: i32,
    #[prost(string, tag="3")]
    pub app_name: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub client_a1_version: u32,
    #[prost(string, tag="5")]
    pub qua: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub open_info: ::core::option::Option<NtLoginOpenInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginOpenInfo {
    #[prost(uint32, tag="1")]
    pub app_id: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginSdkInfo {
    #[prost(uint32, tag="1")]
    pub version: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginSecurityInfo {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginCookie {
    #[prost(string, tag="1")]
    pub cookie_content: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginLongCookie {
    #[prost(bytes="bytes", tag="1")]
    pub content: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginErrorInfo {
    #[prost(uint64, tag="1")]
    pub err_code: u64,
    #[prost(string, tag="2")]
    pub str_tips_title: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub str_tips_content: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub str_jump_wording: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub str_jump_url: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub msg_detail: ::core::option::Option<NtLoginErrorDetail>,
    #[prost(message, repeated, tag="7")]
    pub rpt_msg_button: ::prost::alloc::vec::Vec<NtLoginButton>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginErrorDetail {
    #[prost(message, optional, tag="1")]
    pub msg_need_verify_new_device: ::core::option::Option<NtLoginErrorNeedVerifyNewDevice>,
    #[prost(message, optional, tag="2")]
    pub msg_unregistered: ::core::option::Option<NtLoginErrorUnregistered>,
    #[prost(message, optional, tag="3")]
    pub msg_been_forbiden: ::core::option::Option<NtLoginErrorBeenForbiden>,
    #[prost(message, optional, tag="4")]
    pub msg_nice_account_expire: ::core::option::Option<NtLoginErrorNiceAccountExpire>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginErrorNeedVerifyNewDevice {
    #[prost(bool, tag="1")]
    pub allow_gate_way_verify: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginErrorUnregistered {
    #[prost(string, tag="1")]
    pub unregistered_sig: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginErrorBeenForbiden {
    #[prost(uint32, tag="1")]
    pub area: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginErrorNiceAccountExpire {
    #[prost(string, tag="1")]
    pub expire_sig: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginButton {
    #[prost(string, tag="1")]
    pub wording: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginCommonInfo {
    #[prost(uint32, tag="1")]
    pub face: u32,
    #[prost(string, tag="2")]
    pub nick: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub gender: u32,
    #[prost(uint32, tag="4")]
    pub flag: u32,
    #[prost(uint32, tag="5")]
    pub age: u32,
    #[prost(int32, tag="6")]
    pub svr_flag: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginTgtInfo {
    #[prost(bytes="bytes", tag="1")]
    pub tgt: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub gtkey_tgt: ::prost::bytes::Bytes,
    #[prost(uint32, tag="3")]
    pub tgt_ver: u32,
    #[prost(uint64, tag="4")]
    pub priority: u64,
    #[prost(uint64, tag="5")]
    pub refresh_interval: u64,
    #[prost(uint64, tag="6")]
    pub validate_interval: u64,
    #[prost(uint64, tag="7")]
    pub try_refresh_interval: u64,
    #[prost(uint64, tag="8")]
    pub try_refresh_count: u64,
    #[prost(uint64, tag="9")]
    pub dst_appid: u64,
    #[prost(bytes="bytes", tag="10")]
    pub gtkey_tgtpwd: ::prost::bytes::Bytes,
    #[prost(message, optional, tag="11")]
    pub comm_info: ::core::option::Option<NtLoginCommonInfo>,
    #[prost(bytes="bytes", tag="12")]
    pub sig_session: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="13")]
    pub sig_session_key: ::prost::bytes::Bytes,
    #[prost(uint64, tag="14")]
    pub next_refresh_gap: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginStInfo {
    #[prost(bytes="bytes", tag="1")]
    pub st: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub gtkey_st: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginStHttpInfo {
    #[prost(uint32, tag="1")]
    pub allow_ptlogin: u32,
    #[prost(bytes="bytes", tag="2")]
    pub st_http: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="3")]
    pub gtkey_st_http: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginControlRefreshTime {
    #[prost(uint64, tag="1")]
    pub next_start_refresh_time: u64,
    #[prost(uint64, tag="2")]
    pub expire_time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginTickets {
    #[prost(bytes="bytes", tag="3")]
    pub a1: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="4")]
    pub a2: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="5")]
    pub d2: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="6")]
    pub d2_key: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="7")]
    pub auth_code: ::prost::bytes::Bytes,
    #[prost(message, optional, tag="8")]
    pub tgt_info: ::core::option::Option<NtLoginTgtInfo>,
    #[prost(message, optional, tag="9")]
    pub st_info: ::core::option::Option<NtLoginStInfo>,
    #[prost(bytes="bytes", tag="10")]
    pub sec_extra: ::prost::bytes::Bytes,
    #[prost(message, optional, tag="11")]
    pub st_http_info: ::core::option::Option<NtLoginStHttpInfo>,
    #[prost(message, optional, tag="12")]
    pub a1_refresh_time: ::core::option::Option<NtLoginControlRefreshTime>,
    #[prost(bytes="bytes", tag="13")]
    pub nopicsig: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="14")]
    pub a1_key: ::prost::bytes::Bytes,
    #[prost(uint64, tag="15")]
    pub a1_seq: u64,
    #[prost(message, optional, tag="16")]
    pub a2_refresh_time: ::core::option::Option<NtLoginControlRefreshTime>,
    #[prost(bytes="bytes", tag="17")]
    pub a2_key: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginUserProfile {
    #[prost(bytes="bytes", tag="1")]
    pub nick_name: ::prost::bytes::Bytes,
    #[prost(bool, tag="2")]
    pub register_without_password: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginAccoutInfo {
    #[prost(uint64, tag="1")]
    pub uin: u64,
    #[prost(string, tag="2")]
    pub uid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub user_profile: ::core::option::Option<NtLoginUserProfile>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginIframe {
    #[prost(string, tag="1")]
    pub iframe_sig: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub iframe_randstr: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub iframe_sid: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginSecProtect {
    #[prost(bytes="bytes", tag="1")]
    pub new_device_check_sig: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub unusual_device_check_sig: ::prost::bytes::Bytes,
    #[prost(string, tag="3")]
    pub unusual_device_qr_sig: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub uin_token: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginSecCheck {
    #[prost(string, tag="3")]
    pub iframe_url: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginLoginProcessReqBody {
    #[prost(bool, tag="1")]
    pub need_remind_cancellated_status: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NtLoginLoginProcessRspBody {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a1: ::prost::bytes::Bytes,
    #[prost(message, optional, tag="2")]
    pub iframe: ::core::option::Option<NtLoginIframe>,
    #[prost(bytes="bytes", tag="3")]
    pub new_device_check_succeed_sig: ::prost::bytes::Bytes,
    #[prost(string, tag="4")]
    pub register_succeed_sig: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub login_process_req: ::core::option::Option<NtLoginLoginProcessReqBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="2")]
    pub sec_check: ::core::option::Option<NtLoginSecCheck>,
    #[prost(message, optional, tag="3")]
    pub sec_protect: ::core::option::Option<NtLoginSecProtect>,
    #[prost(message, optional, tag="4")]
    pub account: ::core::option::Option<NtLoginAccoutInfo>,
    #[prost(message, optional, tag="5")]
    pub login_process_rsp: ::core::option::Option<NtLoginLoginProcessRspBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginNewDeviceReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub new_device_check_succeed_sig: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginNewDeviceRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="3")]
    pub account: ::core::option::Option<NtLoginAccoutInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginUnusualDeviceReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a1: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub unusual_device_check_succeed_sig: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginPasswordLoginUnusualDeviceRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="2")]
    pub account: ::core::option::Option<NtLoginAccoutInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginEasyLoginReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a1: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginEasyLoginRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="2")]
    pub sec_check: ::core::option::Option<NtLoginSecCheck>,
    #[prost(message, optional, tag="3")]
    pub sec_protect: ::core::option::Option<NtLoginSecProtect>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginEasyLoginUnusualDeviceReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a1: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub unusual_device_check_succeed_sig: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginEasyLoginUnusualDeviceRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginTgtExchangeFastLoginReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub tgt: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub sec_extra: ::prost::bytes::Bytes,
    #[prost(int32, tag="3")]
    pub code_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginTgtExchangeFastLoginRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginRefreshTicketReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a1: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub nopicsig: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginRefreshTicketRspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="2")]
    pub account: ::core::option::Option<NtLoginAccoutInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginRefreshA2ReqBody {
    #[prost(bytes="bytes", tag="1")]
    pub a2: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="2")]
    pub d2: ::prost::bytes::Bytes,
    #[prost(bytes="bytes", tag="3")]
    pub d2_key: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginRefreshA2RspBody {
    #[prost(message, optional, tag="1")]
    pub tickets: ::core::option::Option<NtLoginTickets>,
    #[prost(message, optional, tag="2")]
    pub account: ::core::option::Option<NtLoginAccoutInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NtLoginCommon {
    #[prost(message, optional, tag="1")]
    pub head: ::core::option::Option<NtLoginHead>,
    #[prost(bytes="bytes", tag="2")]
    pub body: ::prost::bytes::Bytes,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QrLogin {
    #[prost(uint32, tag="1")]
    pub scan_result: u32,
    #[prost(message, optional, tag="2")]
    pub safe_info: ::core::option::Option<SafeInfo>,
    #[prost(message, optional, tag="3")]
    pub risk_info: ::core::option::Option<RiskInfo>,
    #[prost(message, optional, tag="4")]
    pub reject_info: ::core::option::Option<RejectInfo>,
    #[prost(message, optional, tag="5")]
    pub tips_ctrl: ::core::option::Option<TipsCtrl>,
    #[prost(message, optional, tag="6")]
    pub auto_renew_ticket_info: ::core::option::Option<AutoRenewTicketInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SafeInfo {
    #[prost(string, tag="1")]
    pub tips_template: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub login_loc: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub new_tips_template: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskInfo {
    #[prost(string, tag="1")]
    pub tips_template: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub login_loc: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub app_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub new_tips_template: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RejectInfo {
    #[prost(string, tag="1")]
    pub tips: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AutoRenewTicketInfo {
    #[prost(bool, tag="1")]
    pub is_show_switch: bool,
    #[prost(bool, tag="2")]
    pub is_open_switch: bool,
    #[prost(string, tag="3")]
    pub tips_title: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tips_template: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TipsCtrl {
    #[prost(uint32, tag="1")]
    pub normal_tips_color: u32,
    #[prost(bool, tag="2")]
    pub sec_check: bool,
    #[prost(string, tag="3")]
    pub sec_check_tips: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub sec_tips_color: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DevInfo {
    #[prost(string, tag="1")]
    pub dev_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub dev_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GenInfo {
    #[prost(uint32, tag="1")]
    pub client_type: u32,
    #[prost(uint32, tag="2")]
    pub client_ver: u32,
    #[prost(uint32, tag="3")]
    pub client_appid: u32,
    #[prost(uint32, tag="6")]
    pub field6: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QrExtInfo {
    #[prost(message, optional, tag="1")]
    pub dev_info: ::core::option::Option<DevInfo>,
    #[prost(string, tag="2")]
    pub qr_url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub qr_sig: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub gen_info: ::core::option::Option<GenInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScanExtInfo {
    #[prost(bytes="bytes", tag="1")]
    pub guid: ::prost::bytes::Bytes,
    #[prost(string, tag="2")]
    pub imei: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub scan_scene: u32,
    #[prost(bool, tag="4")]
    pub allow_auto_renew_ticket: bool,
    #[prost(bool, tag="5")]
    pub invalid_gen_ticket: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceReport {
    #[prost(string, tag="1")]
    pub bootloader: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proc_version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub code_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub incremental: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub boot_id: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub android_id: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub base_band: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub inner_version: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NtLoginPlatform {
    Unknown = 0,
    Ios = 1,
    Android = 2,
    Symbian = 3,
    Windows = 4,
    Mac = 5,
    Ipad = 6,
    Linux = 7,
    Harmony = 8,
}
impl NtLoginPlatform {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            NtLoginPlatform::Unknown => "NT_LOGIN_PLATFORM_UNKNOWN",
            NtLoginPlatform::Ios => "NT_LOGIN_PLATFORM_IOS",
            NtLoginPlatform::Android => "NT_LOGIN_PLATFORM_ANDROID",
            NtLoginPlatform::Symbian => "NT_LOGIN_PLATFORM_SYMBIAN",
            NtLoginPlatform::Windows => "NT_LOGIN_PLATFORM_WINDOWS",
            NtLoginPlatform::Mac => "NT_LOGIN_PLATFORM_MAC",
            NtLoginPlatform::Ipad => "NT_LOGIN_PLATFORM_IPAD",
            NtLoginPlatform::Linux => "NT_LOGIN_PLATFORM_LINUX",
            NtLoginPlatform::Harmony => "NT_LOGIN_PLATFORM_HARMONY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NT_LOGIN_PLATFORM_UNKNOWN" => Some(Self::Unknown),
            "NT_LOGIN_PLATFORM_IOS" => Some(Self::Ios),
            "NT_LOGIN_PLATFORM_ANDROID" => Some(Self::Android),
            "NT_LOGIN_PLATFORM_SYMBIAN" => Some(Self::Symbian),
            "NT_LOGIN_PLATFORM_WINDOWS" => Some(Self::Windows),
            "NT_LOGIN_PLATFORM_MAC" => Some(Self::Mac),
            "NT_LOGIN_PLATFORM_IPAD" => Some(Self::Ipad),
            "NT_LOGIN_PLATFORM_LINUX" => Some(Self::Linux),
            "NT_LOGIN_PLATFORM_HARMONY" => Some(Self::Harmony),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NtLoginCodeType {
    Authcode = 0,
    Tgt = 1,
    A2 = 2,
    Tgtgt = 3,
}
impl NtLoginCodeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            NtLoginCodeType::Authcode => "NT_LOGIN_CODE_TYPE_AUTHCODE",
            NtLoginCodeType::Tgt => "NT_LOGIN_CODE_TYPE_TGT",
            NtLoginCodeType::A2 => "NT_LOGIN_CODE_TYPE_A2",
            NtLoginCodeType::Tgtgt => "NT_LOGIN_CODE_TYPE_TGTGT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NT_LOGIN_CODE_TYPE_AUTHCODE" => Some(Self::Authcode),
            "NT_LOGIN_CODE_TYPE_TGT" => Some(Self::Tgt),
            "NT_LOGIN_CODE_TYPE_A2" => Some(Self::A2),
            "NT_LOGIN_CODE_TYPE_TGTGT" => Some(Self::Tgtgt),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
