// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Elem {
    #[prost(message, optional, tag="1")]
    pub text: ::core::option::Option<Text>,
    #[prost(message, optional, tag="4")]
    pub not_online_image: ::core::option::Option<NotOnlineImage>,
    #[prost(message, optional, tag="8")]
    pub custom_face: ::core::option::Option<CustomFace>,
    #[prost(message, optional, tag="12")]
    pub rich_msg: ::core::option::Option<RichMsg>,
    #[prost(message, optional, tag="19")]
    pub video_file: ::core::option::Option<VideoFile>,
    #[prost(message, optional, tag="45")]
    pub src_msg: ::core::option::Option<SourceMsg>,
    #[prost(message, optional, tag="51")]
    pub light_app_elem: ::core::option::Option<LightAppElem>,
    #[prost(message, optional, tag="53")]
    pub common_elem: ::core::option::Option<CommonElem>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Text {
    #[prost(string, optional, tag="1")]
    pub text_msg: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub link: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub attr6_buf: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub attr7_buf: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="11")]
    pub buf: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="12")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotOnlineImage {
    #[prost(bytes="bytes", optional, tag="1")]
    pub file_path: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="2")]
    pub file_len: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub download_path: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub old_ver_send_file: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="5")]
    pub img_type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="6")]
    pub previews_image: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="7")]
    pub pic_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="8")]
    pub pic_height: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="9")]
    pub pic_width: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="10")]
    pub res_id: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="11")]
    pub flag: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="12")]
    pub thumb_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="13")]
    pub original: ::core::option::Option<u32>,
    #[prost(string, optional, tag="14")]
    pub big_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="15")]
    pub orig_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="16")]
    pub biz_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="17")]
    pub result: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="18")]
    pub index: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="19")]
    pub op_face_buf: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bool, optional, tag="20")]
    pub old_pic_md5: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag="21")]
    pub thumb_width: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="22")]
    pub thumb_height: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="23")]
    pub file_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="24")]
    pub show_len: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="25")]
    pub download_len: ::core::option::Option<u32>,
    #[prost(string, optional, tag="26")]
    pub url400: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="27")]
    pub width400: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="28")]
    pub height400: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="29")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomFace {
    #[prost(bytes="bytes", optional, tag="1")]
    pub guid: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="2")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub shortcut: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub buffer: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="5")]
    pub flag: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="6")]
    pub old_data: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="7")]
    pub file_id: ::core::option::Option<u32>,
    #[prost(int32, optional, tag="8")]
    pub server_ip: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="9")]
    pub server_port: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="10")]
    pub file_type: ::core::option::Option<i32>,
    #[prost(bytes="bytes", optional, tag="11")]
    pub signature: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(int32, optional, tag="12")]
    pub useful: ::core::option::Option<i32>,
    #[prost(bytes="bytes", optional, tag="13")]
    pub md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="14")]
    pub thumb_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="15")]
    pub big_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="16")]
    pub orig_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="17")]
    pub biz_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="18")]
    pub repeat_index: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="19")]
    pub repeat_image: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="20")]
    pub image_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="21")]
    pub index: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="22")]
    pub width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="23")]
    pub height: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="24")]
    pub source: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag="25")]
    pub size: ::core::option::Option<u32>,
    #[prost(int32, optional, tag="26")]
    pub origin: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="27")]
    pub thumb_width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="28")]
    pub thumb_height: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="29")]
    pub show_len: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="30")]
    pub download_len: ::core::option::Option<i32>,
    #[prost(string, optional, tag="31")]
    pub x400_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="32")]
    pub x400_width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="33")]
    pub x400_height: ::core::option::Option<i32>,
    #[prost(message, optional, tag="34")]
    pub pb_reserve: ::core::option::Option<PbReserve1>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RichMsg {
    #[prost(bytes="bytes", optional, tag="1")]
    pub bytes_template1: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="2")]
    pub service_id: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub bytes_msg_resid: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="4")]
    pub rand: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub seq: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="6")]
    pub flags: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VideoFile {
    #[prost(string, optional, tag="1")]
    pub file_uuid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub file_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="3")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="4")]
    pub file_format: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub file_time: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="6")]
    pub file_size: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="7")]
    pub thumb_width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="8")]
    pub thumb_height: ::core::option::Option<i32>,
    #[prost(bytes="bytes", optional, tag="9")]
    pub thumb_file_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="10")]
    pub source: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(int32, optional, tag="11")]
    pub thumb_file_size: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="12")]
    pub busi_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="13")]
    pub from_chat_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="14")]
    pub to_chat_type: ::core::option::Option<i32>,
    #[prost(bool, optional, tag="15")]
    pub bool_support_progressive: ::core::option::Option<bool>,
    #[prost(int32, optional, tag="16")]
    pub file_width: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="17")]
    pub file_height: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="18")]
    pub sub_busi_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="19")]
    pub video_attr: ::core::option::Option<i32>,
    #[prost(bytes="bytes", repeated, tag="20")]
    pub bytes_thumb_file_urls: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", repeated, tag="21")]
    pub bytes_video_file_urls: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(int32, optional, tag="22")]
    pub thumb_download_flag: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="23")]
    pub video_download_flag: ::core::option::Option<i32>,
    #[prost(bytes="bytes", optional, tag="24")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SourceMsg {
    #[prost(uint32, repeated, packed="false", tag="1")]
    pub orig_seqs: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, optional, tag="2")]
    pub sender_uin: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="3")]
    pub time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub flag: ::core::option::Option<u32>,
    #[prost(bytes="bytes", repeated, tag="5")]
    pub elems: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="6")]
    pub r#type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="7")]
    pub rich_msg: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="8")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="9")]
    pub src_msg: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint64, optional, tag="10")]
    pub to_uin: ::core::option::Option<u64>,
    #[prost(bytes="bytes", optional, tag="11")]
    pub troop_name: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LightAppElem {
    #[prost(bytes="bytes", optional, tag="1")]
    pub bytes_data: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub bytes_msg_resid: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonElem {
    #[prost(uint32, optional, tag="1")]
    pub service_type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub pb_elem: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="3")]
    pub business_type: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileExtra {
    #[prost(message, optional, tag="1")]
    pub file: ::core::option::Option<NotOnlineFile>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextResvAttr {
    #[prost(string, optional, tag="1")]
    pub wording: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="2")]
    pub text_analysis_result: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub at_type: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="4")]
    pub at_member_uin: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="5")]
    pub at_member_tinyid: ::core::option::Option<u64>,
    #[prost(message, optional, tag="6")]
    pub at_member_role_info: ::core::option::Option<RoleInfo>,
    #[prost(message, optional, tag="7")]
    pub at_role_info: ::core::option::Option<RoleInfo>,
    #[prost(message, optional, tag="8")]
    pub at_channel_info: ::core::option::Option<ChannelInfo>,
    #[prost(string, optional, tag="9")]
    pub at_member_uid: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ChannelInfo {
    #[prost(uint64, optional, tag="1")]
    pub guild_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="2")]
    pub channel_id: ::core::option::Option<u64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RoleInfo {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SourceMsgResvAttr {
    #[prost(uint32, optional, tag="2")]
    pub ori_msg_type: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="3")]
    pub source_msg_id: ::core::option::Option<u64>,
    #[prost(string, optional, tag="6")]
    pub sender_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub receiver_uid: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeedsInfo {
    #[prost(uint32, optional, tag="1")]
    pub bus_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag="2")]
    pub file_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="3")]
    pub msg_random: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub ext: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="5")]
    pub feed_flag: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeedsResult {
    #[prost(int32, optional, tag="1")]
    pub ret_code: ::core::option::Option<i32>,
    #[prost(string, optional, tag="2")]
    pub detail: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub file_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="4")]
    pub bus_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub dead_time: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileInfo {
    #[prost(string, optional, tag="1")]
    pub file_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="3")]
    pub file_size: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="4")]
    pub bus_id: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="5")]
    pub uploaded_size: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="6")]
    pub upload_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="7")]
    pub dead_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="8")]
    pub modify_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="9")]
    pub download_times: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="10")]
    pub sha: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="11")]
    pub sha3: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="12")]
    pub md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="13")]
    pub local_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="14")]
    pub uploader_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="15")]
    pub uploader_uin: ::core::option::Option<u64>,
    #[prost(string, optional, tag="16")]
    pub parent_folder_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="17")]
    pub safe_type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="20")]
    pub file_blob_ext: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint64, optional, tag="21")]
    pub owner_uin: ::core::option::Option<u64>,
    #[prost(string, optional, tag="22")]
    pub feed_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="23")]
    pub reserved_field: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileInfoTmem {
    #[prost(uint64, optional, tag="1")]
    pub group_code: ::core::option::Option<u64>,
    #[prost(message, repeated, tag="2")]
    pub files: ::prost::alloc::vec::Vec<FileInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileItem {
    #[prost(uint32, optional, tag="1")]
    pub r#type: ::core::option::Option<u32>,
    #[prost(message, optional, tag="2")]
    pub folder_info: ::core::option::Option<FolderInfo>,
    #[prost(message, optional, tag="3")]
    pub file_info: ::core::option::Option<FileInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FolderInfo {
    #[prost(string, optional, tag="1")]
    pub folder_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub parent_folder_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub folder_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="4")]
    pub create_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub modify_time: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="6")]
    pub create_uin: ::core::option::Option<u64>,
    #[prost(string, optional, tag="7")]
    pub creator_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="8")]
    pub total_file_count: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="9")]
    pub modify_uin: ::core::option::Option<u64>,
    #[prost(string, optional, tag="10")]
    pub modify_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="11")]
    pub used_space: ::core::option::Option<u64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FolderInfoItem {
    #[prost(uint64, optional, tag="1")]
    pub group_code: ::core::option::Option<u64>,
    #[prost(message, repeated, tag="2")]
    pub folders: ::prost::alloc::vec::Vec<FolderInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OverwriteInfo {
    #[prost(string, optional, tag="1")]
    pub file_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="2")]
    pub download_times: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbMultiMsgTransmit {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<CommonMessage>,
    #[prost(message, repeated, tag="2")]
    pub items: ::prost::alloc::vec::Vec<PbMultiMsgItem>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbMultiMsgItem {
    #[prost(string, optional, tag="1")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="2")]
    pub buffer: ::core::option::Option<PbMultiMsgNew>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbMultiMsgNew {
    #[prost(message, repeated, tag="1")]
    pub msg: ::prost::alloc::vec::Vec<CommonMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgInterfaceReq {
    #[prost(message, optional, tag="1")]
    pub recv_req: ::core::option::Option<LongMsgRecvReq>,
    #[prost(message, optional, tag="2")]
    pub send_req: ::core::option::Option<LongMsgSendReq>,
    #[prost(message, optional, tag="15")]
    pub attr: ::core::option::Option<LongMsgAttr>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgInterfaceRsp {
    #[prost(message, optional, tag="1")]
    pub recv_rsp: ::core::option::Option<LongMsgRecvRsp>,
    #[prost(message, optional, tag="2")]
    pub send_rsp: ::core::option::Option<LongMsgSendRsp>,
    #[prost(message, optional, tag="15")]
    pub attr: ::core::option::Option<LongMsgAttr>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LongMsgAttr {
    #[prost(uint32, optional, tag="1")]
    pub sub_cmd: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="2")]
    pub client_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub platform: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub proxy_type: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgPeerInfo {
    #[prost(string, optional, tag="2")]
    pub peer_uid: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgRecvReq {
    #[prost(message, optional, tag="1")]
    pub peer_info: ::core::option::Option<LongMsgPeerInfo>,
    #[prost(string, optional, tag="2")]
    pub res_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="3")]
    pub msg_type: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgSendReq {
    #[prost(uint32, optional, tag="1")]
    pub msg_type: ::core::option::Option<u32>,
    #[prost(message, optional, tag="2")]
    pub peer_info: ::core::option::Option<LongMsgPeerInfo>,
    #[prost(int64, optional, tag="3")]
    pub group_uin: ::core::option::Option<i64>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub payload: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgSendRsp {
    #[prost(string, optional, tag="3")]
    pub res_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LongMsgRecvRsp {
    #[prost(string, optional, tag="3")]
    pub res_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub payload: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonMessage {
    #[prost(message, optional, tag="1")]
    pub routing_head: ::core::option::Option<RoutingHead>,
    #[prost(message, optional, tag="2")]
    pub content_head: ::core::option::Option<ContentHead>,
    #[prost(message, optional, tag="3")]
    pub message_body: ::core::option::Option<MessageBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ContentHead {
    #[prost(int32, optional, tag="1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="2")]
    pub sub_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub c2_c_command: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag="4")]
    pub random: ::core::option::Option<u32>,
    #[prost(int32, optional, tag="5")]
    pub sequence: ::core::option::Option<i32>,
    #[prost(int64, optional, tag="6")]
    pub time: ::core::option::Option<i64>,
    #[prost(int32, optional, tag="7")]
    pub pkg_num: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="8")]
    pub pkg_index: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="9")]
    pub div_seq: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="10")]
    pub auto_reply: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="11")]
    pub client_sequence: ::core::option::Option<i32>,
    #[prost(uint64, optional, tag="12")]
    pub msg_uid: ::core::option::Option<u64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoutingHead {
    #[prost(int64, optional, tag="1")]
    pub from_uin: ::core::option::Option<i64>,
    #[prost(string, optional, tag="2")]
    pub from_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="3")]
    pub from_app_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub from_inst_id: ::core::option::Option<i32>,
    #[prost(int64, optional, tag="5")]
    pub to_uin: ::core::option::Option<i64>,
    #[prost(string, optional, tag="6")]
    pub to_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="7")]
    pub common_c2_c: ::core::option::Option<CommonC2c>,
    #[prost(message, optional, tag="8")]
    pub group: ::core::option::Option<CommonGroup>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonC2c {
    #[prost(int32, optional, tag="1")]
    pub c2_c_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="2")]
    pub service_type: ::core::option::Option<i32>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub sig: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(int64, optional, tag="4")]
    pub from_tiny_id: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="5")]
    pub to_tiny_id: ::core::option::Option<i64>,
    #[prost(string, optional, tag="6")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonGroup {
    #[prost(int64, optional, tag="1")]
    pub group_code: ::core::option::Option<i64>,
    #[prost(int32, optional, tag="2")]
    pub group_type: ::core::option::Option<i32>,
    #[prost(int64, optional, tag="3")]
    pub group_info_seq: ::core::option::Option<i64>,
    #[prost(string, optional, tag="4")]
    pub group_card: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="5")]
    pub group_card_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="6")]
    pub group_level: ::core::option::Option<i32>,
    #[prost(string, optional, tag="7")]
    pub group_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="8")]
    pub ext_group_key_info: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="9")]
    pub msg_flag: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageBody {
    #[prost(message, optional, tag="1")]
    pub rich_text: ::core::option::Option<RichText>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub msg_content: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub msg_encrypt_content: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RichText {
    #[prost(message, optional, tag="1")]
    pub attr: ::core::option::Option<Attr>,
    #[prost(message, repeated, tag="2")]
    pub elems: ::prost::alloc::vec::Vec<Elem>,
    #[prost(message, optional, tag="3")]
    pub not_online_file: ::core::option::Option<NotOnlineFile>,
    #[prost(message, optional, tag="4")]
    pub ptt: ::core::option::Option<Ptt>,
    #[prost(message, optional, tag="5")]
    pub tmp_ptt: ::core::option::Option<TmpPtt>,
    #[prost(message, optional, tag="6")]
    pub trans211_tmp_msg: ::core::option::Option<Trans211TmpMsg>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attr {
    #[prost(int32, optional, tag="1")]
    pub code_page: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="2")]
    pub time: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub play_mode_random: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub color: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub size: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="6")]
    pub tab_effect: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="7")]
    pub char_set: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="8")]
    pub pitch_and_family: ::core::option::Option<i32>,
    #[prost(string, optional, tag="9")]
    pub font_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="10")]
    pub reserve_data: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotOnlineFile {
    #[prost(uint32, optional, tag="1")]
    pub file_type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub sig: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="3")]
    pub file_uuid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub file_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="5")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="6")]
    pub file_size: ::core::option::Option<u64>,
    #[prost(bytes="bytes", optional, tag="7")]
    pub note: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="8")]
    pub reserved: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="9")]
    pub sub_cmd: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="10")]
    pub micro_cloud: ::core::option::Option<u32>,
    #[prost(bytes="bytes", repeated, tag="11")]
    pub file_urls: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="12")]
    pub download_flag: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="50")]
    pub danger_level: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="51")]
    pub life_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="52")]
    pub upload_time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="53")]
    pub abs_file_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="54")]
    pub client_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="55")]
    pub expire_time: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="56")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="57")]
    pub file_id_crc_media: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ptt {
    #[prost(uint32, optional, tag="1")]
    pub file_type: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="2")]
    pub src_uin: ::core::option::Option<u64>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub file_uuid: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub file_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="5")]
    pub file_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="6")]
    pub file_size: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="7")]
    pub reserve: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="8")]
    pub file_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="9")]
    pub server_ip: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="10")]
    pub server_port: ::core::option::Option<u32>,
    #[prost(bool, optional, tag="11")]
    pub valid: ::core::option::Option<bool>,
    #[prost(bytes="bytes", optional, tag="12")]
    pub signature: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="13")]
    pub shortcut: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(string, optional, tag="14")]
    pub file_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="15")]
    pub magic_ptt_index: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="16")]
    pub voice_switch: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="17")]
    pub ptt_url: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="18")]
    pub group_file_key: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="19")]
    pub time: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="20")]
    pub down_para: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="29")]
    pub format: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="30")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", repeated, tag="31")]
    pub ptt_urls: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="32")]
    pub download_flag: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TmpPtt {
    #[prost(uint32, optional, tag="1")]
    pub file_type: ::core::option::Option<u32>,
    #[prost(bytes="bytes", optional, tag="2")]
    pub file_uuid: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="3")]
    pub file_md5: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="4")]
    pub file_name: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="5")]
    pub file_size: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="6")]
    pub ptt_times: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="7")]
    pub user_type: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="8")]
    pub ptt_trans_flag: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="9")]
    pub busi_type: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="10")]
    pub msg_id: ::core::option::Option<u64>,
    #[prost(bytes="bytes", optional, tag="30")]
    pub pb_reserve: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(bytes="bytes", optional, tag="31")]
    pub ptt_encode_data: ::core::option::Option<::prost::bytes::Bytes>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trans211TmpMsg {
    #[prost(bytes="bytes", optional, tag="1")]
    pub msg_body: ::core::option::Option<::prost::bytes::Bytes>,
    #[prost(uint32, optional, tag="2")]
    pub c2_c_cmd: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgPush {
    #[prost(message, optional, tag="1")]
    pub common_message: ::core::option::Option<CommonMessage>,
    #[prost(bool, optional, tag="5")]
    pub push_notify_flag: ::core::option::Option<bool>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbSendMsgReq {
    #[prost(message, optional, tag="1")]
    pub routing_head: ::core::option::Option<SendRoutingHead>,
    #[prost(message, optional, tag="2")]
    pub content_head: ::core::option::Option<SendContentHead>,
    #[prost(message, optional, tag="3")]
    pub message_body: ::core::option::Option<MessageBody>,
    #[prost(int32, optional, tag="4")]
    pub client_sequence: ::core::option::Option<i32>,
    #[prost(uint32, optional, tag="5")]
    pub random: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbSendMsgResp {
    #[prost(int32, optional, tag="1")]
    pub result: ::core::option::Option<i32>,
    #[prost(string, optional, tag="2")]
    pub err_msg: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag="3")]
    pub send_time: ::core::option::Option<i64>,
    #[prost(uint32, optional, tag="10")]
    pub msg_info_flag: ::core::option::Option<u32>,
    #[prost(int32, optional, tag="11")]
    pub sequence: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="14")]
    pub client_sequence: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SendContentHead {
    #[prost(uint32, optional, tag="1")]
    pub pkg_num: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="2")]
    pub pkg_index: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub div_seq: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub auto_reply: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRoutingHead {
    #[prost(message, optional, tag="1")]
    pub c2_c: ::core::option::Option<C2c>,
    #[prost(message, optional, tag="2")]
    pub group: ::core::option::Option<Grp>,
    #[prost(message, optional, tag="15")]
    pub trans0_x211: ::core::option::Option<Trans0X211>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct C2c {
    #[prost(int64, optional, tag="1")]
    pub peer_uin: ::core::option::Option<i64>,
    #[prost(string, optional, tag="2")]
    pub peer_uid: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Grp {
    #[prost(int64, optional, tag="1")]
    pub group_uin: ::core::option::Option<i64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trans0X211 {
    #[prost(int64, optional, tag="1")]
    pub to_uin: ::core::option::Option<i64>,
    #[prost(uint32, optional, tag="2")]
    pub cc_cmd: ::core::option::Option<u32>,
    #[prost(string, optional, tag="8")]
    pub uid: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetC2cMsgReq {
    #[prost(int64, optional, tag="1")]
    pub peer_uin: ::core::option::Option<i64>,
    #[prost(string, optional, tag="2")]
    pub peer_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="3")]
    pub start_sequence: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub end_sequence: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetC2cMsgRsp {
    #[prost(uint32, optional, tag="1")]
    pub retcode: ::core::option::Option<u32>,
    #[prost(string, optional, tag="2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="3")]
    pub start_sequence: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub end_sequence: ::core::option::Option<u32>,
    #[prost(message, repeated, tag="7")]
    pub messages: ::prost::alloc::vec::Vec<CommonMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoGetGroupMsg {
    #[prost(message, optional, tag="1")]
    pub info: ::core::option::Option<SsoGetGroupMsgInfo>,
    #[prost(uint32, optional, tag="2")]
    pub filter: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoGetGroupMsgInfo {
    #[prost(int64, optional, tag="1")]
    pub group_uin: ::core::option::Option<i64>,
    #[prost(int32, optional, tag="2")]
    pub start_sequence: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub end_sequence: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetGroupMsgRsp {
    #[prost(uint32, optional, tag="1")]
    pub ret_code: ::core::option::Option<u32>,
    #[prost(string, optional, tag="2")]
    pub error_msg: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub body: ::core::option::Option<SsoGetGroupMsgRspBody>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetGroupMsgRspBody {
    #[prost(uint32, optional, tag="1")]
    pub retcode: ::core::option::Option<u32>,
    #[prost(string, optional, tag="2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="3")]
    pub group_uin: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub start_sequence: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub end_sequence: ::core::option::Option<u32>,
    #[prost(message, repeated, tag="6")]
    pub messages: ::prost::alloc::vec::Vec<CommonMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetRoamMsgReq {
    #[prost(string, optional, tag="1")]
    pub peer_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag="2")]
    pub time: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="3")]
    pub random: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="4")]
    pub count: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub direction: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoGetRoamMsgRsp {
    #[prost(string, optional, tag="3")]
    pub peer_uid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="4")]
    pub is_complete: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag="5")]
    pub timestamp: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="6")]
    pub random: ::core::option::Option<u32>,
    #[prost(message, repeated, tag="7")]
    pub messages: ::prost::alloc::vec::Vec<CommonMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbReserve1 {
    #[prost(int32, optional, tag="1")]
    pub sub_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub field3: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub field4: ::core::option::Option<i32>,
    #[prost(string, optional, tag="9")]
    pub summary: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="10")]
    pub field10: ::core::option::Option<i32>,
    #[prost(message, optional, tag="21")]
    pub field21: ::core::option::Option<PbReserve2>,
    #[prost(string, optional, tag="31")]
    pub field31: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PbReserve2 {
    #[prost(int32, optional, tag="1")]
    pub field1: ::core::option::Option<i32>,
    #[prost(string, optional, tag="2")]
    pub field2: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="3")]
    pub field3: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub field4: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub field5: ::core::option::Option<i32>,
    #[prost(string, optional, tag="7")]
    pub md5_str: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
