// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoSyncPush {
    #[prost(uint32, tag="1")]
    pub result: u32,
    #[prost(string, tag="2")]
    pub err_msg: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub push_flag: u32,
    #[prost(uint32, tag="4")]
    pub push_seq: u32,
    #[prost(uint32, tag="5")]
    pub retry_flag: u32,
    #[prost(message, repeated, tag="6")]
    pub group_nodes: ::prost::alloc::vec::Vec<GroupNode>,
    #[prost(message, optional, tag="7")]
    pub notifications: ::core::option::Option<GroupSystemNotifications>,
    #[prost(message, optional, tag="8")]
    pub sys_notifications: ::core::option::Option<SystemNotifications>,
    #[prost(uint32, tag="10")]
    pub use_init_cache_data: u32,
    #[prost(message, optional, tag="11")]
    pub guild_nodes: ::core::option::Option<GuildNode>,
    #[prost(uint32, tag="12")]
    pub discuss_list_flag: u32,
    #[prost(uint32, tag="13")]
    pub roam_msg_optimize_flag: u32,
    #[prost(uint32, tag="14")]
    pub group_guild_flag: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupNode {
    #[prost(uint64, tag="1")]
    pub group_code: u64,
    #[prost(uint64, tag="2")]
    pub group_seq: u64,
    #[prost(uint64, tag="3")]
    pub read_msg_seq: u64,
    #[prost(uint64, tag="4")]
    pub mask: u64,
    #[prost(uint64, tag="5")]
    pub longest_msg_time: u64,
    #[prost(bool, tag="6")]
    pub has_message: bool,
    #[prost(uint64, tag="8")]
    pub latest_msg_time: u64,
    #[prost(string, tag="9")]
    pub peer_name: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub longest_msg_seq: u64,
    #[prost(uint64, tag="11")]
    pub uin_flag_ex2: u64,
    #[prost(uint32, tag="12")]
    pub important_msg_latest_seq: u32,
    #[prost(uint32, tag="13")]
    pub group_max_event_seq: u32,
    #[prost(uint32, tag="14")]
    pub random: u32,
    #[prost(uint32, tag="15")]
    pub need_to_check_seq_on_aio_open: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GuildNode {
    #[prost(uint64, tag="1")]
    pub peer_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupSystemNotifications {
    #[prost(message, repeated, tag="3")]
    pub infos: ::prost::alloc::vec::Vec<GroupSystemNotificationsInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemNotifications {
    #[prost(message, repeated, tag="4")]
    pub infos: ::prost::alloc::vec::Vec<SystemNotificationsInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupSystemNotificationsInfo {
    #[prost(int64, tag="3")]
    pub group_code: i64,
    #[prost(uint32, tag="4")]
    pub start_seq: u32,
    #[prost(uint32, tag="5")]
    pub end_seq: u32,
    #[prost(message, repeated, tag="6")]
    pub messages: ::prost::alloc::vec::Vec<super::super::message::v2::CommonMessage>,
    #[prost(int64, tag="8")]
    pub last_speak_timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemNotificationsInfo {
    #[prost(int64, tag="1")]
    pub peer_uin: i64,
    #[prost(string, tag="2")]
    pub peer_uid: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub last_speak_timestamp: i64,
    #[prost(message, repeated, tag="8")]
    pub messages: ::prost::alloc::vec::Vec<super::super::message::v2::CommonMessage>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoHeartBeatRequest {
    #[prost(uint32, tag="1")]
    pub r#type: u32,
    #[prost(message, optional, tag="2")]
    pub local_silence: ::core::option::Option<SilenceState>,
    #[prost(uint32, tag="3")]
    pub battery_state: u32,
    #[prost(uint64, tag="4")]
    pub time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoHeartBeatResponse {
    #[prost(uint64, tag="3")]
    pub interval: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SilenceState {
    #[prost(uint32, tag="1")]
    pub local_silence: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushParams {
    #[prost(message, repeated, tag="4")]
    pub online_devices: ::prost::alloc::vec::Vec<OnlineDevice>,
    #[prost(message, optional, tag="6")]
    pub guild_params: ::core::option::Option<GuildParams>,
    #[prost(string, tag="7")]
    pub err_msg: ::prost::alloc::string::String,
    #[prost(uint32, tag="9")]
    pub group_msg_storage_time: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GuildParams {
    #[prost(uint32, tag="1")]
    pub guild_flag: u32,
    #[prost(uint32, tag="2")]
    pub guild_switch_flag: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnlineDevice {
    #[prost(uint32, tag="1")]
    pub inst_id: u32,
    #[prost(uint32, tag="2")]
    pub client_type: u32,
    #[prost(uint32, tag="3")]
    pub state: u32,
    #[prost(uint32, tag="4")]
    pub plat_id: u32,
    #[prost(string, tag="5")]
    pub plat_type: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub new_client_type: u32,
    #[prost(string, tag="7")]
    pub device_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoC2cMsgCookie {
    #[prost(uint64, tag="1")]
    pub c2_c_last_msg_time: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SsoC2cSyncInfo {
    #[prost(message, optional, tag="1")]
    pub c2_c_msg_cookie: ::core::option::Option<SsoC2cMsgCookie>,
    #[prost(uint64, tag="2")]
    pub c2_c_last_msg_time: u64,
    #[prost(message, optional, tag="3")]
    pub last_c2_c_msg_cookie: ::core::option::Option<SsoC2cMsgCookie>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(string, tag="1")]
    pub dev_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub dev_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub os_ver: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub brand: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vendor_os_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OnlineBusinessInfo {
    #[prost(uint32, tag="1")]
    pub notify_switch: u32,
    #[prost(uint32, tag="2")]
    pub bind_uin_notify_switch: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterInfo {
    #[prost(string, tag="1")]
    pub guid: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub kick_pc: u32,
    #[prost(string, tag="3")]
    pub build_ver: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub is_first_register_proxy_online: u32,
    #[prost(uint32, tag="5")]
    pub locale_id: u32,
    #[prost(message, optional, tag="6")]
    pub device_info: ::core::option::Option<DeviceInfo>,
    #[prost(uint32, tag="7")]
    pub set_mute: u32,
    #[prost(uint32, tag="8")]
    pub register_vendor_type: u32,
    #[prost(uint32, tag="9")]
    pub reg_type: u32,
    #[prost(message, optional, tag="10")]
    pub business_info: ::core::option::Option<OnlineBusinessInfo>,
    #[prost(uint32, tag="11")]
    pub battery_status: u32,
    #[prost(int32, optional, tag="12")]
    pub field12: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NormalConfig {
    #[prost(map="uint32, int32", tag="1")]
    pub int_cfg: ::std::collections::HashMap<u32, i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CurAppState {
    #[prost(uint32, tag="1")]
    pub is_delay_request: u32,
    #[prost(uint32, tag="2")]
    pub app_status: u32,
    #[prost(uint32, tag="3")]
    pub silence_status: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoInfoSyncRequest {
    #[prost(uint32, tag="1")]
    pub sync_flag: u32,
    #[prost(uint32, tag="2")]
    pub req_random: u32,
    #[prost(uint32, tag="4")]
    pub cur_active_status: u32,
    #[prost(uint64, tag="5")]
    pub group_last_msg_time: u64,
    #[prost(message, optional, tag="6")]
    pub c2_c_sync_info: ::core::option::Option<SsoC2cSyncInfo>,
    #[prost(message, optional, tag="8")]
    pub normal_config: ::core::option::Option<NormalConfig>,
    #[prost(message, optional, tag="9")]
    pub register_info: ::core::option::Option<RegisterInfo>,
    #[prost(map="uint32, uint32", tag="10")]
    pub unknown: ::std::collections::HashMap<u32, u32>,
    #[prost(message, optional, tag="11")]
    pub app_state: ::core::option::Option<CurAppState>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(string, tag="2")]
    pub msg: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoSyncInfoResponse {
    #[prost(message, optional, tag="7")]
    pub register_response: ::core::option::Option<RegisterResponse>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoUnregister {
    #[prost(int32, tag="1")]
    pub reg_type: i32,
    #[prost(message, optional, tag="2")]
    pub device_info: ::core::option::Option<DeviceInfo>,
    #[prost(int32, tag="3")]
    pub user_trigger: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThirdPartyLoginResponse {
    #[prost(uint64, tag="1")]
    pub seq: u64,
    #[prost(message, optional, tag="9")]
    pub common_info: ::core::option::Option<RespCommonInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RespCommonInfo {
    #[prost(uint32, tag="10")]
    pub need_verify_scenes: u32,
    #[prost(message, optional, tag="11")]
    pub rsp_nt: ::core::option::Option<RspNt>,
    #[prost(uint32, tag="12")]
    pub a1_seq: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RspNt {
    #[prost(string, tag="1")]
    pub uid: ::prost::alloc::string::String,
    #[prost(bytes="bytes", tag="2")]
    pub ua2: ::prost::bytes::Bytes,
}
// @@protoc_insertion_point(module)
